from blog import BlogHandler
from signup import SignupHandler
from register import Register
from login import Login
from logout import Logout
from comment import CommentHandler
from delete_comment import DeleteComment
from delete_post import DeletePost
from edit_comment import EditComment
from edit_post import EditPost
from front_page import FrontPage
from new_post import NewPost
from post_page import PostPage
from rating import Rating
